files = main.cpp \
		Warlock.cpp \
		ASpell.cpp \
		Fwoosh.cpp \
		ATarget.cpp \
		Dummy.cpp \
		Fireball.cpp \
		Polymorph.cpp \
		BrickWall.cpp \
		SpellBook.cpp \
		TargetGenerator.cpp

all:
	clear & c++ -Wall -Wextra -Werror $(files) -I ./

run: all
	./a.out | cat -e