# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: inwagner <inwagner@student.42sp.org.br>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/06/03 18:25:54 by inwagner          #+#    #+#              #
#    Updated: 2024/06/03 18:25:55 by inwagner         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Variables
NAME		:=	megaphone
SRC			:=	megaphone.cpp

all:
	@c++ -Wall -Wextra -Werror -std=c++98 megaphone.cpp -o $(NAME)

clean:
	@echo "Nothing to be done."

fclean:
	@rm $(NAME)

re: fclean all